using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Options;
using Nomori.Marketplace.Core.Configuration;
using Nomori.Marketplace.Core.Customers;

namespace Nomori.Marketplace.Data.Customers;

#pragma warning disable CA1725 // Compact SQL implementation uses local parameter names.

public sealed class SqlCustomerAccountDataStore(IOptions<DatabaseOptions> options) : ICustomerAccountDataStore
{
    public async Task<IReadOnlyList<CustomerAddress>> GetAddressesAsync(int customerId, CancellationToken ct) { await using var c=await Open(ct); await using var q=c.CreateCommand(); q.CommandText="SELECT Id,CustomerId,FirstName,LastName,Company,Address1,Address2,City,StateProvince,CountryCode,ZipPostalCode,PhoneNumber,IsDefault FROM CustomerAddress WHERE CustomerId=@CustomerId ORDER BY IsDefault DESC,Id DESC"; q.Parameters.AddWithValue("@CustomerId",customerId); await using var r=await q.ExecuteReaderAsync(ct); var items=new List<CustomerAddress>(); while(await r.ReadAsync(ct))items.Add(ReadAddress(r)); return items; }
    public async Task<CustomerAddress?> GetAddressAsync(int customerId,int addressId,CancellationToken ct)=>(await GetAddressesAsync(customerId,ct)).SingleOrDefault(x=>x.Id==addressId);
    public async Task<int> SaveAddressAsync(CustomerAddress a,CancellationToken ct) { await using var c=await Open(ct); await using var tx=await c.BeginTransactionAsync(ct); if(a.IsDefault){await using var clear=c.CreateCommand();clear.Transaction=(SqlTransaction)tx;clear.CommandText="UPDATE CustomerAddress SET IsDefault=0 WHERE CustomerId=@CustomerId";clear.Parameters.AddWithValue("@CustomerId",a.CustomerId);await clear.ExecuteNonQueryAsync(ct);} await using var q=c.CreateCommand();q.Transaction=(SqlTransaction)tx;q.CommandText=a.Id==0?"INSERT INTO CustomerAddress (CustomerId,FirstName,LastName,Company,Address1,Address2,City,StateProvince,CountryCode,ZipPostalCode,PhoneNumber,IsDefault) OUTPUT INSERTED.Id VALUES (@CustomerId,@FirstName,@LastName,@Company,@Address1,@Address2,@City,@StateProvince,@CountryCode,@ZipPostalCode,@PhoneNumber,@IsDefault)":"UPDATE CustomerAddress SET FirstName=@FirstName,LastName=@LastName,Company=@Company,Address1=@Address1,Address2=@Address2,City=@City,StateProvince=@StateProvince,CountryCode=@CountryCode,ZipPostalCode=@ZipPostalCode,PhoneNumber=@PhoneNumber,IsDefault=@IsDefault WHERE Id=@Id AND CustomerId=@CustomerId"; Params(q,a); object? v=a.Id==0?await q.ExecuteScalarAsync(ct):await q.ExecuteNonQueryAsync(ct); await tx.CommitAsync(ct); return a.Id==0?(int)v!:a.Id; }
    public async Task<bool> DeleteAddressAsync(int customerId,int addressId,CancellationToken ct){await using var c=await Open(ct);await using var q=c.CreateCommand();q.CommandText="DELETE FROM CustomerAddress WHERE Id=@Id AND CustomerId=@CustomerId";q.Parameters.AddWithValue("@Id",addressId);q.Parameters.AddWithValue("@CustomerId",customerId);return await q.ExecuteNonQueryAsync(ct)>0;}
    public async Task<CustomerAttributeSet> GetAttributesAsync(int customerId,CancellationToken ct){await using var c=await Open(ct);await using var q=c.CreateCommand();q.CommandText="SELECT d.SystemName,d.Name,d.DataType,d.IsRequired,d.DisplayOrder,v.Value FROM CustomerAttributeDefinition d LEFT JOIN CustomerAttributeValue v ON v.CustomerAttributeDefinitionId=d.Id AND v.CustomerId=@CustomerId ORDER BY d.DisplayOrder";q.Parameters.AddWithValue("@CustomerId",customerId);await using var r=await q.ExecuteReaderAsync(ct);var d=new List<CustomerAttributeDefinition>();var v=new Dictionary<string,string>();while(await r.ReadAsync(ct)){var key=r.GetString(0);d.Add(new(key,r.GetString(1),r.GetString(2),r.GetBoolean(3),r.GetInt32(4)));if(!r.IsDBNull(5))v[key]=r.GetString(5);}return new(d,v);}
    public async Task SaveAttributesAsync(int customerId,IReadOnlyDictionary<string,string> values,CancellationToken ct){await using var c=await Open(ct);foreach(var pair in values){await using var q=c.CreateCommand();q.CommandText="MERGE CustomerAttributeValue AS target USING (SELECT @CustomerId CustomerId, Id DefinitionId FROM CustomerAttributeDefinition WHERE SystemName=@SystemName) source ON target.CustomerId=source.CustomerId AND target.CustomerAttributeDefinitionId=source.DefinitionId WHEN MATCHED THEN UPDATE SET Value=@Value WHEN NOT MATCHED THEN INSERT (CustomerId,CustomerAttributeDefinitionId,Value) VALUES (source.CustomerId,source.DefinitionId,@Value);";q.Parameters.AddWithValue("@CustomerId",customerId);q.Parameters.AddWithValue("@SystemName",pair.Key);q.Parameters.AddWithValue("@Value",pair.Value);await q.ExecuteNonQueryAsync(ct);}}
    public async Task CreateEmailChangeAsync(int id,string email,string hash,DateTime expires,CancellationToken ct){await using var c=await Open(ct);await using var q=c.CreateCommand();q.CommandText="UPDATE CustomerEmailChangeToken SET Used=1 WHERE CustomerId=@CustomerId AND Used=0; INSERT INTO CustomerEmailChangeToken (CustomerId,NewEmail,TokenHash,ExpiresOnUtc,CreatedOnUtc) VALUES (@CustomerId,@NewEmail,@TokenHash,@ExpiresOnUtc,SYSUTCDATETIME())";q.Parameters.AddWithValue("@CustomerId",id);q.Parameters.AddWithValue("@NewEmail",email);q.Parameters.AddWithValue("@TokenHash",hash);q.Parameters.AddWithValue("@ExpiresOnUtc",expires);await q.ExecuteNonQueryAsync(ct);}
    public async Task<(int CustomerId,string NewEmail)?> ConsumeEmailChangeAsync(string hash,DateTime now,CancellationToken ct){await using var c=await Open(ct);await using var q=c.CreateCommand();q.CommandText="UPDATE CustomerEmailChangeToken SET Used=1 OUTPUT INSERTED.CustomerId,INSERTED.NewEmail WHERE TokenHash=@TokenHash AND Used=0 AND ExpiresOnUtc>@Now";q.Parameters.AddWithValue("@TokenHash",hash);q.Parameters.AddWithValue("@Now",now);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?(r.GetInt32(0),r.GetString(1)):null;}
    public async Task<bool> EmailExistsAsync(string email,CancellationToken ct){await using var c=await Open(ct);await using var q=c.CreateCommand();q.CommandText="SELECT COUNT(1) FROM Customer WHERE Email=@Email";q.Parameters.AddWithValue("@Email",email);return (int)(await q.ExecuteScalarAsync(ct)??0)>0;}
    public async Task ApplyEmailChangeAsync(int id,string email,DateTime now,CancellationToken ct){await using var c=await Open(ct);await using var q=c.CreateCommand();q.CommandText="UPDATE Customer SET Email=@Email,EmailVerified=1,EmailVerifiedOnUtc=@Now,RequireReLogin=1 WHERE Id=@Id";q.Parameters.AddWithValue("@Email",email);q.Parameters.AddWithValue("@Now",now);q.Parameters.AddWithValue("@Id",id);await q.ExecuteNonQueryAsync(ct);}
    private async Task<SqlConnection> Open(CancellationToken ct){var c=new SqlConnection(options.Value.ConnectionString);await c.OpenAsync(ct);return c;} private static CustomerAddress ReadAddress(SqlDataReader r)=>new(){Id=r.GetInt32(0),CustomerId=r.GetInt32(1),FirstName=r.GetString(2),LastName=r.GetString(3),Company=N(r,4),Address1=r.GetString(5),Address2=N(r,6),City=r.GetString(7),StateProvince=N(r,8),CountryCode=r.GetString(9),ZipPostalCode=N(r,10),PhoneNumber=r.GetString(11),IsDefault=r.GetBoolean(12)};private static string? N(SqlDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static void Params(SqlCommand q,CustomerAddress a){q.Parameters.AddWithValue("@Id",a.Id);q.Parameters.AddWithValue("@CustomerId",a.CustomerId);q.Parameters.AddWithValue("@FirstName",a.FirstName);q.Parameters.AddWithValue("@LastName",a.LastName);q.Parameters.AddWithValue("@Company",(object?)a.Company??DBNull.Value);q.Parameters.AddWithValue("@Address1",a.Address1);q.Parameters.AddWithValue("@Address2",(object?)a.Address2??DBNull.Value);q.Parameters.AddWithValue("@City",a.City);q.Parameters.AddWithValue("@StateProvince",(object?)a.StateProvince??DBNull.Value);q.Parameters.AddWithValue("@CountryCode",a.CountryCode);q.Parameters.AddWithValue("@ZipPostalCode",(object?)a.ZipPostalCode??DBNull.Value);q.Parameters.AddWithValue("@PhoneNumber",a.PhoneNumber);q.Parameters.AddWithValue("@IsDefault",a.IsDefault);}
}

#pragma warning restore CA1725
